import { Restaurant } from "./demo-data";

export const elCorralRestaurant: Restaurant = {
  id: "el-corral-mexican-grill",
  name: "El Corral Mexican Grill & Bar",
  tagline: "Authentic Mexican Restaurant & Bar",
  phone: "(832) 230-8024",
  address: "6321 N Eldridge Pkwy, Houston, TX 77041",
  hours: "Abierto todos los días",
  heroImage: "",
  whatsapp: "18322308024",
  categories: [
    {
      id: "appetizers",
      name: "Appetizers",
      icon: "🧀",
      items: [
        {
          id: "a1",
          name: "Botana del Corral",
          description: "Two quesadillas, four mini flautas, and four nachos bites with guacamole, sour cream, and pico de gallo. Choice of chicken, beef, or combo.",
          price: 16.99,
          image: "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?w=800&q=80",
          popular: true,
        },
        {
          id: "a2",
          name: "Chile con Queso",
          description: "Housemade chili dip with melted cheese",
          price: 7.99,
          image: "https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=800&q=80",
        },
        {
          id: "a3",
          name: "Guacamole",
          description: "Mashed avocado mixed with chopped tomato and cilantro",
          price: 7.99,
          image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
        },
        {
          id: "a4",
          name: "Guacamole Botana",
          description: "Chicharrón, queso fresco and mashed avocado mixed with chopped tomato",
          price: 10.99,
          image: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=800&q=80",
        },
        {
          id: "a5",
          name: "Queso Flameado",
          description: "Hot melted cheese served with avocado and pico de gallo. Mushrooms, chorizo, or shrimp options.",
          price: 9.99,
          image: "https://images.unsplash.com/photo-1628557044797-f21d174c8f58?w=800&q=80",
        },
        {
          id: "a6",
          name: "Nachos Plate",
          description: "Choice of beef fajita or chicken fajita served with refried beans, cheese, guacamole, pico de gallo, and sour cream",
          price: 11.99,
          image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&q=80",
        },
      ],
    },
    {
      id: "parilladas",
      name: "Parrilladas",
      icon: "🔥",
      items: [
        {
          id: "pr1",
          name: "Classic Fajitas",
          description: "Beef fajita or chicken fajita served with rice, beans, guacamole, pico de gallo, salad, and three handmade tortillas",
          price: 18.99,
          image: "https://images.unsplash.com/photo-1624300629298-e9de39c13be5?w=800&q=80",
          popular: true,
        },
        {
          id: "pr2",
          name: "Fajitas Combo",
          description: "Beef, chicken fajita, and shrimp or sausage. Served with rice, beans, guacamole, pico de gallo, salad, and three handmade tortillas",
          price: 20.49,
          image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
          popular: true,
        },
        {
          id: "pr3",
          name: "Fajitas Poblanas",
          description: "Beef fajita, chicken fajita, or combo, topped with poblana sauce. Served with rice, beans, guacamole, pico de gallo, salad, and three handmade tortillas",
          price: 20.99,
          image: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800&q=80",
        },
        {
          id: "pr4",
          name: "Parrillada del Corral",
          description: "Beef fajita, chicken fajita, sausage, and shrimp momia grill. Served with rice, beans, guacamole, pico de gallo, salad, and three handmade tortillas",
          price: 22.49,
          image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
          popular: true,
        },
        {
          id: "pr5",
          name: "T-bone Steak",
          description: "Served with rice, french fries, small salad, guacamole, pico de gallo, and three handmade tortillas",
          price: 19.49,
          image: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
        },
        {
          id: "pr6",
          name: "Costillas de Res",
          description: "Three grilled short ribs. Served with rice, beans, small salad, guacamole, pico de gallo, and three handmade tortillas",
          price: 19.49,
          image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
        },
        {
          id: "pr7",
          name: "Molcajete",
          description: "Ribs, chicken, and two shrimp. Served with poblano chili, rice, charro beans, small salad, guacamole, pico de gallo, and three handmade tortillas",
          price: 21.99,
          image: "https://images.unsplash.com/photo-1653543693229-4b29269a4e5a?w=800&q=80",
        },
        {
          id: "pr8",
          name: "Poblano Shrimp Skillet",
          description: "Fresh roasted poblano pepper stuffed with melted cheese and ranchera sauce over grilled onions, with five large shrimps. Served with fresh house salad, charro beans, and rice",
          price: 19.49,
          image: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=800&q=80",
        },
      ],
    },
    {
      id: "caldos",
      name: "Caldos",
      icon: "🍲",
      items: [
        {
          id: "c1",
          name: "Caldo de Pollo",
          description: "Chicken and vegetable soup. Served with rice, cilantro, onion, and three handmade tortillas",
          price: 13.49,
          image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
        },
        {
          id: "c2",
          name: "Caldo de Res",
          description: "Beef and vegetable soup. Served with rice, cilantro, onion, rice, and three handmade tortillas",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1603105037880-880cd4f0647d?w=800&q=80",
        },
        {
          id: "c3",
          name: "Tortilla Soup",
          description: "Chicken and vegetable soup. Topped with tortilla chips, avocado, monterrey jack cheese. Served with rice, cilantro, and three handmade tortillas",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800&q=80",
          popular: true,
        },
        {
          id: "c4",
          name: "Pozole",
          description: "Pork and hominy soup. Served with onion, cilantro, cabbage, radish, and three tostadas. Weekends only.",
          price: 13.49,
          image: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=800&q=80",
        },
        {
          id: "c5",
          name: "Caldo de Camarón",
          description: "Shrimp and vegetable soup, cilantro, onion, rice, and three handmade tortillas or bread",
          price: 15.99,
          image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
        },
        {
          id: "c6",
          name: "Caldo de Mariscos",
          description: "Seafood and vegetable soup, cilantro, onion, rice, and three handmade tortillas or bread",
          price: 15.99,
          image: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&q=80",
        },
      ],
    },
    {
      id: "platos-del-corral",
      name: "Platos del Corral",
      icon: "🍽️",
      items: [
        {
          id: "pc1",
          name: "Pechuga Cancún",
          description: "Grilled chicken breast with two shrimp momia. Topped with chipotle cream and melted cheese",
          price: 18.49,
          image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=800&q=80",
          popular: true,
        },
        {
          id: "pc2",
          name: "Tampiqueña",
          description: "8oz. tender beef steak, two cheese enchiladas with housemade gravy. Served with french fries, rice, and salad",
          price: 18.49,
          image: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
        },
        {
          id: "pc3",
          name: "Chile Relleno",
          description: "Roasted poblano pepper stuffed with ground beef or cheese and topped with ranchero sauce and queso fresco",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1599789197514-47270cd526b4?w=800&q=80",
        },
        {
          id: "pc4",
          name: "Burrito Dinner",
          description: "Served with refried beans, lettuce, tomato, avocado, sour cream, cheese, topped with chile con queso",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
        },
        {
          id: "pc5",
          name: "Chimichanga",
          description: "Deep fried burrito stuffed with cheese, your choice of meat and topped with chile con queso and chili gravy",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1584208632869-05fa2b2a5934?w=800&q=80",
        },
      ],
    },
    {
      id: "enchiladas",
      name: "Enchiladas",
      icon: "🫔",
      items: [
        {
          id: "e1",
          name: "Enchiladas al Carbón",
          description: "Three corn tortillas filled with choice of meat. Topped with ranchero sauce, green sauce, mole, or housemade gravy. Beef fajita.",
          price: 15.49,
          image: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800&q=80",
          popular: true,
        },
        {
          id: "e2",
          name: "Enchiladas de Queso",
          description: "Three corn tortillas filled with cheese. Topped with your choice of sauce",
          price: 13.99,
          image: "https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?w=800&q=80",
        },
        {
          id: "e3",
          name: "Enchiladas Mexicana",
          description: "Three corn tortillas filled with queso fresco. Topped with housemade red sauce, queso fresco, avocado, and sour cream",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?w=800&q=80",
        },
      ],
    },
    {
      id: "mariscos",
      name: "Mariscos",
      icon: "🦐",
      items: [
        {
          id: "m1",
          name: "Coctel de Camarón",
          description: "Shrimp in housemade tomato cocktail sauce. Served with avocado, pico de gallo, and crackers",
          price: 13.99,
          image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
          popular: true,
        },
        {
          id: "m2",
          name: "Mojarra Frita",
          description: "Deep fried whole tilapia. Served with rice, fries, small salad, and three handmade tortillas or bread",
          price: 14.99,
          image: "https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800&q=80",
        },
        {
          id: "m3",
          name: "Camarones a la Diabla",
          description: "Six large shrimp sauteed with chipotle sauce, bell pepper, onion, and mushroom",
          price: 16.49,
          image: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=800&q=80",
          spicy: true,
        },
        {
          id: "m4",
          name: "Camarones al Mojo de Ajo",
          description: "Six large shrimp sauteed with garlic butter sauce, bell pepper, onion, and mushroom",
          price: 16.49,
          image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
        },
        {
          id: "m5",
          name: "Camarones Momia",
          description: "Five grilled bacon wrapped jalapeño stuffed with shrimp and monterrey jack cheese. Served with rice, small salad, avocado, and chipotle ranch",
          price: 20.99,
          image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800&q=80",
          popular: true,
        },
        {
          id: "m6",
          name: "Pescado Vallarta",
          description: "White fish fillet and shrimp sauteed in chipotle cream sauce",
          price: 19.49,
          image: "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=800&q=80",
        },
      ],
    },
    {
      id: "street-food",
      name: "Corral Street Food",
      icon: "🌮",
      items: [
        {
          id: "sf1",
          name: "Mini Tacos",
          description: "Five al pastor pork or beef fajita street style tacos. Topped with cilantro and served with grilled onions and charro beans",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
          popular: true,
        },
        {
          id: "sf2",
          name: "Gringas al Pastor",
          description: "Two flour tortilla quesadillas with al pastor pork and grilled onions. Served with rice and charro beans",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=800&q=80",
        },
        {
          id: "sf3",
          name: "Taco Pirata",
          description: "Large flour tortilla filled with grilled beef, monterrey jack cheese, grilled onion, and avocado. Served with rice and charro beans",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1628260412297-a3377e45006f?w=800&q=80",
        },
        {
          id: "sf4",
          name: "Flautas",
          description: "Rolled crispy corn tortilla filled with beef or chicken. Topped with queso fresco, guacamole, and sour cream. Served with rice, beans, and small salad",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1599789197514-47270cd526b4?w=800&q=80",
        },
        {
          id: "sf5",
          name: "La Gran Quesadilla",
          description: "Large flour tortilla filled with cheese and choice of meat. Served with guacamole, rice, beans, and sour cream",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=800&q=80",
        },
        {
          id: "sf6",
          name: "Barbacoa",
          description: "Slow cooked beef. Served with cilantro, onions, and handmade tortillas. Half pound or full pound.",
          price: 10.99,
          image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
        },
        {
          id: "sf7",
          name: "Mole",
          description: "Chicken in a traditional housemade mole sauce. Served with rice and choice of three handmade tortillas",
          price: 15.99,
          image: "https://images.unsplash.com/photo-1585672840563-f2af2ced55c9?w=800&q=80",
        },
      ],
    },
    {
      id: "tacos",
      name: "Tacos",
      icon: "🌮",
      items: [
        {
          id: "tc1",
          name: "Taco Al Pastor",
          description: "Marinated pork with cilantro and onion. Handmade corn or flour tortilla.",
          price: 2.99,
          image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
          popular: true,
        },
        {
          id: "tc2",
          name: "Taco de Barbacoa",
          description: "Slow cooked beef with cilantro and onion",
          price: 2.99,
          image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
        },
        {
          id: "tc3",
          name: "Taco de Pechuga",
          description: "Chicken breast with pico de gallo",
          price: 3.69,
          image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&q=80",
        },
        {
          id: "tc4",
          name: "Taco al Carbón",
          description: "Grilled beef with pico de gallo",
          price: 3.69,
          image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
        },
        {
          id: "tc5",
          name: "Taco de Camarón",
          description: "Shrimp with lettuce and tomato",
          price: 3.69,
          image: "https://images.unsplash.com/photo-1611250188496-e966043a0629?w=800&q=80",
        },
        {
          id: "tc6",
          name: "Taco de Pescado",
          description: "Fish with lettuce and tomato",
          price: 3.69,
          image: "https://images.unsplash.com/photo-1512838243191-e81e8f66f1fd?w=800&q=80",
        },
        {
          id: "tc7",
          name: "Crispy Taco",
          description: "Ground beef with lettuce and tomato",
          price: 2.99,
          image: "https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800&q=80",
        },
      ],
    },
    {
      id: "tex-mex",
      name: "Platos Tex Mex",
      icon: "⭐",
      items: [
        {
          id: "tx1",
          name: "El Corral",
          description: "Two cheese enchiladas with housemade gravy and one hard shell ground beef taco",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615?w=800&q=80",
        },
        {
          id: "tx2",
          name: "El Monterrey",
          description: "Two hard shell ground beef tacos, one cheese enchilada with housemade gravy",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1613514785940-daed07799d9b?w=800&q=80",
        },
        {
          id: "tx3",
          name: "El Houston",
          description: "Three hard shell tacos with chicken breast, beef fajita, or ground beef. Topped with cheddar cheese, lettuce, tomato and sour cream",
          price: 14.49,
          image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
          popular: true,
        },
      ],
    },
    {
      id: "breakfast",
      name: "Desayunos",
      icon: "🍳",
      items: [
        {
          id: "br1",
          name: "El Skillet",
          description: "Skillet style beef, chicken, chorizo, or bacon, two eggs, potatoes, bell pepper, tomato, onion, cheese, and mushrooms",
          price: 12.99,
          image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80",
          popular: true,
        },
        {
          id: "br2",
          name: "Barbacoa con Huevo",
          description: "Slow cooked beef and eggs",
          price: 12.99,
          image: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
        },
        {
          id: "br3",
          name: "Chilaquiles del Corral",
          description: "Fried tortilla chips, choice of green or red salsa. Choice of beef or chicken. Topped with queso fresco, avocado, sour cream, onions, and cilantro. Served with two eggs.",
          price: 17.49,
          image: "https://images.unsplash.com/photo-1653543693229-4b29269a4e5a?w=800&q=80",
          popular: true,
        },
        {
          id: "br4",
          name: "Huevos Rancheros",
          description: "Two fried eggs with ranchera sauce",
          price: 8.99,
          image: "https://images.unsplash.com/photo-1528735000049-389aa69e3b4a?w=800&q=80",
        },
        {
          id: "br5",
          name: "Breakfast El Corral",
          description: "Tender beef steak, two eggs and two cheese enchiladas",
          price: 15.99,
          image: "https://images.unsplash.com/photo-1558030006-450675393462?w=800&q=80",
        },
        {
          id: "br6",
          name: "Breakfast Tacos",
          description: "Corn or flour tortilla. Choice of bacon, chorizo, ham, potato, sausage, cactus, beef fajita, machacado, or chicken breast",
          price: 2.69,
          image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
        },
      ],
    },
  ],
};
